#define PACKAGE_NAME "fnt"
#define PACKAGE_NAME_LONG "Fast Neurite Tracer"
#define PACKAGE_NAME_LONG_LC "fast-neurite-tracer"
#define PACKAGE_DESCRIPTION "Semi-automatic neurite tracing with tera-bytes of imaging data"
#define PACKAGE_VERSION "0.99.1"
#define PACKAGE_URL "https://fast-neurite-tracer.sourceforge.io/"
#define PACKAGE_BUGREPORT "https://sourceforge.net/p/fast-neurite-tracer/tickets/"
#define PACKAGE_AUTHORS "GOU Lingfeng <goulf@ion.ac.cn>"
#define PACKAGE_ORG "Lab. of Biological Network Computation, Institute of Neuroscience, China"
#define PACKAGE_DOMAIN "yanlab.org"
#define PACKAGE_PLUGINDIR "lib/fnt-plugins"
#define PACKAGE_DATADIR "share"
