[
    "nmtC|charm|Frontal|ACgG|ACC"
    # "nmtC|charm|Frontal|lat_PFC|area_8A"
    "nmtC|charm|Frontal|lat_PFC|dlPFC"
    "nmtC|charm|Frontal|lat_PFC|vlPFC"
    "nmtC|charm|Frontal|motor|M1/PM"
    "nmtC|charm|Frontal|motor|SMA/preSMA"
    "nmtC|charm|Frontal|OFC"
    # "nmtC|charm|Frontal|OFC|lat_OFC"
    # "nmtC|charm|Frontal|OFC|med_OFC"
    "nmtC|sarm|tel|BG|Str"
    # "nmtI|charm|Frontal|ACgG"
    "nmtI|charm|Frontal|ACgG|ACC"
    "nmtI|charm|Frontal|ACgG|MCC"
    # "nmtI|charm|Frontal|lat_PFC|area_8A"   ### Can be added if typesetting space is enough
    "nmtI|charm|Frontal|lat_PFC|dlPFC"
    "nmtI|charm|Frontal|lat_PFC|vlPFC"
    "nmtI|charm|Frontal|motor|M1/PM"
    "nmtI|charm|Frontal|motor|SMA/preSMA"
    "nmtI|charm|Frontal|OFC"
    # "nmtI|charm|Frontal|OFC|caudal_OFC"
    # "nmtI|charm|Frontal|OFC|lat_OFC"
    # "nmtI|charm|Frontal|OFC|med_OFC"
    "nmtI|charm|Parietal|IPL"
    # "nmtI|charm|Parietal|IPL|area_7_in_IPL"
    # "nmtI|charm|Parietal|IPL|lat_IPS"
    "nmtI|charm|Parietal|PMC"
    # "nmtI|charm|Parietal|PMC|PCgG"
    "nmtI|charm|Parietal|SI/SII|SII"
    # "nmtI|charm|Temporal"
    # "nmtI|charm|Temporal|floor_of_ls|Ins/Pi"
    "nmtI|charm|Temporal|ITC|STSf"
    "nmtI|charm|Temporal|ITC|TE"
    # "nmtI|charm|Temporal|ITC|TEO"
    "nmtI|charm|Temporal|STG/STSd|STGr/STSd"
    # "nmtI|sarm|di|EpiThal"   ### Can be added if typesetting space is enough
    "nmtI|sarm|di|Hy"
    # "nmtI|sarm|di|Hy|PHy"
    # "nmtI|sarm|di|Hy|THy"
    # "nmtI|sarm|di|PreThal"
    # "nmtI|sarm|di|PrT|p1Rt"
    # "nmtI|sarm|di|PrT|PCR"
    "nmtI|sarm|di|Thal"
    "nmtI|sarm|mes|Mid"
    "nmtI|sarm|met|Pons"
    "nmtI|sarm|myel|Med"
    # "nmtI|sarm|tel|Amy"
    "nmtI|sarm|tel|BG|Pd"
    "nmtI|sarm|tel|BG|Str"
    # "nmtI|sarm|tel|LVPal|LPal"
    # "nmtI|sarm|tel|LVPal|LPal|Cl"
]




