[
    "nmtI|sarm|di|Thal|MThal|ILThal|CL-PC"
    "nmtI|sarm|di|Thal|MThal|MD"
    "nmtI|sarm|di|Thal|PThal|Pul"
    "nmtI|sarm|di|Thal|Rt"
    "nmtI|sarm|di|Thal|VThal|PNThal|VA"

    # "nmtI|sarm|di|Thal|MThal|ILThal|SG"
    # "nmtI|sarm|di|Thal|MLThal|PVA"
    # "nmtI|sarm|di|Thal|MLThal|PVP"
    
    # "nmtI|sarm|di|EpiThal|Hb"
    # "nmtI|sarm|di|PreThal|ZI-H"
    # "nmtI|sarm|di|Thal|MLThal"
    # "nmtI|sarm|di|Thal|MThal|A+"
    # "nmtI|sarm|di|Thal|MThal|ILThal"
    # "nmtI|sarm|di|Thal|PThal"
    # "nmtI|sarm|di|Thal|VThal|CbThal|VLPD"
    # "nmtI|sarm|di|Thal|VThal|PNThal|VA"
    # "nmtI|sarm|di|Thal|VThal|PNThal|VLA"
    # "nmtI|sarm|mes|Mid"
    # "nmtI|sarm|mes|Mid|DMid"
    # "nmtI|sarm|mes|Mid|VMid"
    # "nmtI|sarm|tel|BG|Str|DStr|Cd"
    # "nmtI|sarm|tel|BG|Str|DStr|ic"
    # # "nmtC|sarm|di|EpiThal"
    # # "nmtC|sarm|di|PreThal"
    # # "nmtC|sarm|di|Thal"
    # # "nmtC|sarm|mes|Mid"
    # # "nmtC|sarm|tel|BG"
]
