[
    "nmtC|sarm|mes|Mid|DMid|Co|SC"
    "nmtC|sarm|mes|Mid|DMid|PAGR|PAG"
    "nmtC|sarm|mes|Mid|VMid|DA_Mid|SN"
    "nmtC|sarm|mes|Mid|VMid|DA_Mid|VTA"
    "nmtC|sarm|met|Pons|VPons|Pn+|Pn"
    "nmtI|sarm|di|Hy|THy|DTHy|LHy"
    #"nmtI|sarm|di|Hy|THy|DTHy|STh"
    "nmtI|sarm|di|Thal|MThal|MD"
    "nmtI|sarm|di|Thal|Rt"
    "nmtI|sarm|di|Thal|VThal|PNThal|VA"
    "nmtI|sarm|di|Thal|PThal|Pul"
    "nmtI|sarm|mes|Mid|DMid|Co|SC"
    "nmtI|sarm|mes|Mid|DMid|PAGR|PAG"
    "nmtI|sarm|mes|Mid|VMid|DA_Mid|SN"
    "nmtI|sarm|mes|Mid|VMid|DA_Mid|VTA"
    "nmtI|sarm|met|Pons|VPons|Pn+|Pn"
    "nmtI|sarm|tel|BG|Pd"
    #"nmtI|sarm|tel|BG|Str|DStr|Cd|CdH"

    # "nmtI|sarm|di|EpiThal"
    # "nmtI|sarm|di|Hy|THy|DTHy"
    # "nmtI|sarm|di|PreThal|ZI-H"
    # "nmtI|sarm|di|PrT"
    # "nmtI|sarm|di|Thal|MLThal|PVP"
    # "nmtI|sarm|di|Thal|MThal|ILThal"
    # "nmtI|sarm|di|Thal|PThal"
    # "nmtI|sarm|di|Thal|Rt"
    # "nmtI|sarm|di|Thal|VThal|PNThal"
    # "nmtI|sarm|di|Thal|VThal|SpThal"
    # "nmtI|sarm|mes|Mid|DMid"
    # "nmtI|sarm|mes|Mid|LMid"
    # "nmtI|sarm|mes|Mid|MMid"
    # "nmtI|sarm|mes|Mid|VMid"
    # "nmtI|sarm|met|Pons|VPons"
    # "nmtI|sarm|tel|BG|Pd|GP"
    # "nmtC|sarm|di|PrT"
    # # "nmtC|sarm|di|Thal|MLThal|PVP"
    # # "nmtC|sarm|di|Thal|MThal|ILThal"
    # # "nmtC|sarm|di|Thal|MThal|MD"
    # # "nmtC|sarm|mes|Mid|DMid"
    # # "nmtC|sarm|mes|Mid|LMid"
    # # "nmtC|sarm|mes|Mid|MMid"
    # # "nmtC|sarm|mes|Mid|VMid"
    # # "nmtC|sarm|met|Pons|VPons"
]
