[
    ### "nmtI|sarm|di|EpiThal"
    "nmtI|sarm|di|Hy"
    ### "nmtI|sarm|di|Hy|PHy|DPHy|PH"
    ### "nmtI|sarm|di|Hy|THy|DTHy|AH"
    # "nmtI|sarm|di|Hy|THy|DTHy|LHy"
    ### "nmtI|sarm|di|Hy|THy|DTHy|STh"
    "nmtI|sarm|di|Thal"
    # "nmtI|sarm|di|Thal|MThal|MD"
    # "nmtI|sarm|di|Thal|Rt"
    "nmtI|sarm|mes|Mid"
    ### "nmtI|sarm|mes|Mid|DMid|Co|ICoC|ICo"
    # "nmtI|sarm|mes|Mid|DMid|PAGR|PAG"
    ### "nmtI|sarm|mes|Mid|MMid|raphe_Mid|DR"
    ### "nmtI|sarm|mes|Mid|VMid|DA_Mid|RF"
    # "nmtI|sarm|mes|Mid|VMid|DA_Mid|VTA"
    "nmtI|sarm|met|Pons"
    ### "nmtI|sarm|met|Pons|DPons|PBC"
    # "nmtI|sarm|met|Pons|VPons|retPons|PnC"
    "nmtI|sarm|myel|Med"
    ### "nmtI|sarm|myel|Med|IMed|MedRaphe|RMg"
    ### "nmtI|sarm|tel|Amy|pAmy|vpAmy|BM"
    ### "nmtI|sarm|tel|Amy|spAmy|mAmy|Me"
    ### "nmtI|sarm|tel|Amy|spAmy|stAmy|Ce"
    "nmtI|sarm|tel|BG|Pd"
    "nmtI|sarm|tel|BG|Str"
    ### "nmtI|sarm|tel|BG|Str|VStr|Acb"
    ### "nmtI|sarm|tel|DSP|ST"

    "nmtC|sarm|di|Hy"
    ### "nmtC|sarm|di|Hy|PHy|DPHy|PH"
    # "nmtC|sarm|di|Hy|THy|DTHy|LHy"
    "nmtC|sarm|di|Thal"
    # "nmtC|sarm|di|Thal|MThal|MD"
    "nmtC|sarm|mes|Mid"
    # "nmtC|sarm|mes|Mid|DMid|PAGR|PAG"
    ### "nmtC|sarm|mes|Mid|MMid|raphe_Mid|DR"
    # "nmtC|sarm|mes|Mid|VMid|DA_Mid|VTA"
    "nmtC|sarm|met|Pons"
    # "nmtC|sarm|met|Pons|VPons|retPons|PnC"
    "nmtC|sarm|myel|Med"
    ### "nmtC|sarm|myel|Med|IMed|MedRaphe|RMg"
    "nmtC|sarm|tel|BG|Pd"
    "nmtC|sarm|tel|BG|Str"
]
