[
    "nmtC|charm|Frontal|lat_PFC|dlPFC|area_8B"
    "nmtC|charm|Frontal|lat_PFC|dlPFC|rostral_dlPFC|area_46d"
    "nmtC|charm|Frontal|lat_PFC|dlPFC|rostral_dlPFC|area_9"
    "nmtC|charm|Frontal|lat_PFC|vlPFC|caudal_vlPFC|area_44"
    "nmtC|charm|Frontal|lat_PFC|vlPFC|caudal_vlPFC|area_45"
    "nmtC|charm|Frontal|lat_PFC|vlPFC|rostral_vlPFC|area_12r/l"
    # "nmtC|charm|Frontal|lat_PFC|vlPFC|rostral_vlPFC|area_12r/l|area_12r"
    "nmtC|charm|Frontal|lat_PFC|vlPFC|rostral_vlPFC|area_46v/f"
    # "nmtC|charm|Frontal|lat_PFC|vlPFC|rostral_vlPFC|area_46v/f|area_46v"
    "nmtI|charm|Frontal|lat_PFC|dlPFC|area_8B"
    "nmtI|charm|Frontal|lat_PFC|dlPFC|rostral_dlPFC|area_46d"
    "nmtI|charm|Frontal|lat_PFC|dlPFC|rostral_dlPFC|area_9"
    "nmtI|charm|Frontal|lat_PFC|vlPFC|caudal_vlPFC|area_44"
    "nmtI|charm|Frontal|lat_PFC|vlPFC|caudal_vlPFC|area_45"
    "nmtI|charm|Frontal|lat_PFC|vlPFC|rostral_vlPFC|area_12r/l"
    # "nmtI|charm|Frontal|lat_PFC|vlPFC|rostral_vlPFC|area_12r/l|area_12r"
    "nmtI|charm|Frontal|lat_PFC|vlPFC|rostral_vlPFC|area_46v/f"
    # "nmtI|charm|Frontal|lat_PFC|vlPFC|rostral_vlPFC|area_46v/f|area_46v"
]
