[
    "nmtI|sarm|di|Thal|MThal|MD"
    # "nmtI|sarm|di|Thal|Rt"
    "nmtI|sarm|di|Thal|VThal|PNThal|VA"
    "nmtI|sarm|di|Hy|PHy|DPHy|PH"
    "nmtI|sarm|di|Hy|THy|DTHy|LHy"
    # "nmtI|sarm|tel|BG|Str"
    "nmtI|sarm|tel|BG|Pd"
    # "nmtI|sarm|mes|Mid"
    "nmtI|sarm|mes|Mid|DMid|PAGR|PAG"
    "nmtI|sarm|mes|Mid|DMid|Co|SC"
    "nmtI|sarm|mes|Mid|MMid|raphe_Mid|DR"
    "nmt|sarm|mes|Mid|VMid|DA_Mid|SN"
    "nmtI|sarm|mes|Mid|VMid|DA_Mid|VTA"
    "nmtI|sarm|met|Pons"
    "nmtI|sarm|myel|Med"

    "nmtC|sarm|di|Thal|MThal|MD"
    # "nmtC|sarm|di|Thal|Rt"
    # "nmtC|sarm|di|Thal|VThal|PNThal|VA"
    "nmtC|sarm|di|Hy|PHy|DPHy|PH"
    "nmtC|sarm|di|Hy|THy|DTHy|LHy"
    # "nmtC|sarm|tel|BG|Str"
    # "nmtC|sarm|tel|BG|Pd"
    # "nmtC|sarm|mes|Mid"
    "nmtC|sarm|mes|Mid|DMid|PAGR|PAG"
    "nmtC|sarm|mes|Mid|DMid|Co|SC"
    "nmtC|sarm|mes|Mid|MMid|raphe_Mid|DR"
    # "nmtC|sarm|mes|Mid|VMid|DA_Mid|SN"
    "nmtC|sarm|mes|Mid|VMid|DA_Mid|VTA"
    "nmtC|sarm|met|Pons"
    "nmtC|sarm|myel|Med"
    
    
    # # "nmt|sarm|di|EpiThal|Hb"
    # # "nmt|sarm|di|PreThal|ZI-H"
    # "nmt|sarm|di|Thal|MLThal"
    # # "nmt|sarm|di|Thal|MLThal|IMD"
    # # "nmt|sarm|di|Thal|MLThal|PVP"
    # # "nmt|sarm|di|Thal|MLThal|Re-Rh-Xi"
    # "nmt|sarm|di|Thal|MThal|A+|AR|A"
    # "nmt|sarm|di|Thal|MThal|ILThal"
    # # "nmt|sarm|di|Thal|MThal|ILThal|CMn-PF"
    # # "nmt|sarm|di|Thal|MThal|ILThal|Lim"
    # # "nmt|sarm|di|Thal|MThal|ILThal|SPFC"
    # "nmt|sarm|di|Thal|VThal"
    # # "nmt|sarm|di|Thal|VThal|CbThal|VLPD"
    # # "nmt|sarm|di|Thal|VThal|PNThal|VLA"
    # # "nmt|sarm|di|Thal|VThal|SpThal|VM"
]
